### ISSUE TITLE
Please give .deb file for Ubuntu

### ISSUE THREAD

**Issue by jmz-bit** [Stor-Network/stor-blockchain#2]
I like this project.

Chia and good forks are providing .deb file for easy install under Ubuntu.

This is easies way to install or upgrade app for many people who are running Chia and forks.

So please give .deb file to make our life easier a bit.

**Comment by Stor-Network** [comment]
.deb released in Stor 1.0.4 -> [https://github.com/Stor-Network/stor-blockchain/releases](https://github.com/Stor-Network/stor-blockchain/releases)
